### PR TITLE
Updated user configuration (username and password), updated README

### PR DESCRIPTION
**Pull request by parth-io**
Hi,

I found this repo to be very useful as a new NUS student, but if you are a non-CS student I imagine it would be difficult to set up. So this commit just makes it (slightly) easier for a new user to set it up.

Let me know if you have any thoughts on the edits/if I need to change anything.

### CODE REVIEW

**Comment by halfwhole** [comment]
Hi, thanks for this PR! Good to hear that you find it useful, and the changes look great :) It definitely helps to ask for credentials rather than having to set it up manually.

Perhaps we could afford to .gitignore the `CONFIG.yaml` file, we can auto-create it the first time round instead? Also the tests along with chai/mocha are probably not that useful as well, but otherwise it looks good to me

**Comment by parth-io** [comment]
Hi, thanks for your comments! I've made the edits as you suggested.

I apologise for this late follow-up, NUS CS just hit me like a runaway train and I completely forgot about this PR.

Let me know if anything's amiss!

**Review by halfwhole — COMMENTED** [review]
It looks good mostly! It looks though like there's some sensitive info in an intermediate commit. I could squash and merge it so it doesn't appear in the git commit history, but you might also want to squash and force-push this branch yourself too (so it doesn't appear on github as well).

**Comment by parth-io** [comment]
Hi,

Thanks for pointing that out. I've fixed it, but GitHub automatically closed this PR so I've opened a new PR.

**Pull request closed without merging**
